overlay/etc/wireless/interfaces/eth0, overlay/etc/wireless/sdio
remove obsolete interfaces directory
update sdio to use /sbin/mmc
=> update /etc/wireless modules

overlay/etc/init.d/rcS
=> export tz var for webui

.github/scripts/list_configs.sh, .github/workflows/build.yaml
=> [no ci] Add workflow script & config

package/webui/files/var/www/a/imp-config.js, package/webui/files/var/www/cgi-bin/config-imp.cgi, package/webui/files/var/www/cgi-bin/p/common.cgi
latest libimp_control.so required
=> add function to autoposition osd

package/prudynt-t/files/S96record
Allow record service parsing of password with special characters except double quote
=> Allow record service parsing of password with special characters

package/zerotier-one/files/S90zerotier
Start by default if installed, allow disabling with optional config file
=> Update S90zerotier to reverse startup logic

overlay/lower/etc/init.d/rc.common, overlay/lower/etc/network/interfaces.d/eth0, package/thingino-webui/files/etc/init.d/S50httpd
tested on my ethernet capable cam.
had to add 3 seconds post up to allow network to link, otherwise first ping always had a packet drop
=> disable portal if eth has active connection

scripts/tabulate_gpio.py
Here's the script I used for the table if you deem it useful.
=> tabulate GPIO settings in github markdown table

overlay/lower/etc/init.d/S49ntpd, overlay/lower/etc/ntp.conf, overlay/lower/usr/share/udhcpc/default.script, package/thingino-webui/files/var/www/x/config-time.cgi, package/thingino-webui/files/var/www/x/j/reset-ntp.cgi
For reference: https://github.com/armcc/udhcp/blob/master/README.udhcpc
=> udhcpc [option 42] configuration for ntp

overlay/lower/etc/init.d/S49ntpd, overlay/lower/etc/ntp.conf, overlay/lower/usr/share/udhcpc/default.script, package/thingino-webui/files/var/www/x/config-time.cgi, package/thingino-webui/files/var/www/x/j/reset-ntp.cgi
Reverts themactep/thingino-firmware#154
`Starting ntpd: cp: can't stat '/rom/etc/ntp.conf': No such file or directory`
needs more work with dhcp server not sending ntp settings.
=> Revert "udhcpc [option 42] configuration for ntp"

package/thingino-webui/files/var/www/x/preview.cgi
I'm getting 7-8 here (which is roughly 40Mbit/s)
=> add fps estimate to preview page

overlay/lower/usr/sbin/motion, overlay/lower/usr/sbin/sysupgrade, package/onvif-simple-server/0002-change-config-file-and-dir-names.patch, package/onvif-simple-server/files/S96onvif_discovery, package/onvif-simple-server/files/S97onvif_notify, package/onvif-simple-server/files/onvif.conf, package/onvif-simple-server/onvif-simple-server.mk, package/thingino-webui/files/var/www/x/config-rtsp.cgi, package/thingino-webui/files/var/www/x/plugin-motion.cgi
This adds motion detection to ONVIF and requires https://github.com/gtxaspec/prudynt-t/pull/16/files to be merged first
=> onvif-simple-server: add onvif_notify_server and track motion alarm

scripts/rootfs_script.sh
saves about 42k fro the squashfs rootfs image
=> Remove unnecessary exfat tools

package/thingino-webui/files/var/www/x/config-osd.cgi, package/thingino-webui/files/var/www/x/preview.cgi
=> possible browser crash on preview fix.

package/prudynt-t/files/S96record, package/prudynt-t/files/record, package/thingino-webui/files/var/www/x/config-record.cgi
init script - Make destination directory instead of failing if it doesn't exist
record script - remove avi format
webui cofig - remove avi format
=> Fixes for local recording

overlay/lower/usr/sbin/sysupgrade
Adding wireguard to the list of running services during sysupgrade. https://discord.com/channels/1086012062649565286/1209383244710027284/1305214006734360616
=> Update sysupgrade to permit upgrade over wireguard

environment/wyze-cp3.uenv.txt
=> Added red led for Wyze Cam Pan v3

overlay/lower/etc/init.d/S05led
=> Fix gpio test

package/thingino-ffmpeg/thingino-ffmpeg.mk
https://github.com/opensensor/light-object-detect
=> Enable options for remote image detect

package/thingino-webui/files/www/x/service-videorec.cgi
=> videorec: split recordings into 1hr dirs to avoid FAT max numfile limits

package/onvif-simple-server/files/onvif.conf
Support was added in https://github.com/gtxaspec/prudynt-t/pull/78
=> onvif: enable AAC backchannel

Config.sensor.in, thingino.mk
=> Add config options to build sc5336 sensor used in cinnado d1 3k

package/thingino-webui/files/www/x/config-streamer.cgi, package/thingino-webui/files/www/x/preview.cgi, package/thingino-webui/files/www/x/service-motion.cgi
=> thingino-webui: Restore protocol to WebSocket constructor URLs
