themactep/thingino-firmware

overlay/etc/init.d/S09mmc

Added support for gpio_mmc_power gpio variable from u-boot Removed stop case which attempted to unload the jz_mmc driver, this can lead to lockups as it's not cleanly supported by the driver.

overlay: update s09mmc init.d script

---

overlay/etc/init.d/S50dropbear

adapt init script to generate the ssh key for dropbear on firstboot; then save to env; restore from ENV if key is missing on overlay.
how to generate the key for uEnv.txt:
`dropbearkey -t ed25519 -f /tmp/test >/dev/null 2>&1; gzip -c /tmp/test | base64 | tr -d '\n'; echo \n;rm -f /tmp/test`
```
/dev/null 2>&1; gzip -c /tmp/test | base64 | tr -d '\n'; echo \n
H4sIAAAAAAAAAwFTAKz/AAAAC3NzaC1lZDI1NTE5AAAAQLccuUS/KjMbkK0Xady/eb/fC44qj14IC/yAj28gA5C+MxrmQw3AOprf4SaHtyKrCl3VhMf8yCSkxv4xhaFYJ7ihqOxMUwAAAA==n
```

save dropbear key to env

---

configs/testing/exp_t31l_sc2336_atbm6031_kernel44
external.mk
package/prudynt-t/prudynt-t.mk

* Minimal changes to get 4.4 image working without mods
Depends on:
* https://github.com/gtxaspec/prudynt-t/pull/3
* https://github.com/themactep/ingenic-sdk/pull/7
Open Questions:
I am still building this with my own toolchain build that I compiled against the 4.4 headers.   Noticed that the toolchain fragments reference the 3_10 kernel sources.
For example, this diff captures how I built locally to verify my changes (but I am not sure what the effect of the 3.10 toolchain would be).
```
diff --git a/configs/fragments/templates/toolchain.download.fragment b/configs/fragments/templates/toolchain.download.fragment
index 2a9228f1..f297ead7 100644
--- a/configs/fragments/templates/toolchain.download.fragment
+++ b/configs/fragments/templates/toolchain.download.fragment
@@ -1,7 +1,7 @@ …
```

Changes to support t31 4.4

---

package/onvif-simple-server/files/onvif.conf

Adds get_position command and redirects move_* output to /dev/null to prevent their output being injected as HTTP headers in ONVIF responses.
- The get_position command needs to be supported in order for Frigate (and perhaps other similar systems) to enable PTZ control
- The output of the `move_*` commands gets dumped into the HTTP response (before/in the HTTP headers), which leads to errors being logged by Frigate whenever it requests PTZ moves as it sees them as invalid/malformed headers

ONVIF PTZ improvements

---

package/onvif-simple-server/files/S96onvif

I don't know why but getopt is unable to parse double quotes in this string.
If I run manually the daemon with double quotes it works, but not inside S96onvif.
I removed them, it's not a problem because the string doesn't contain spaces.
This patch fixes ProbeMatches and Hello responses and allows onvif clients to run properly when discovery is used.

Remove double quotes in S96onvif

---

package/onvif-simple-server/files/S96onvif
package/onvif-simple-server/files/onvif.conf

This pr adds two parameters to specify the max horizontal and vertical steps used by onvif.
The init script reads them from u-boot env writes them to /etc/onvif.conf
And finally, it sets the shell commands to move the cam using AbsoluteMove and RelativeMove requests.

Fix ptz aboslute and relative moves

---

package/thingino-webui/files/var/www/cgi-bin/mjpeg.cgi

- corrected type in Connection: close
- added HTTP/1.1 Cache-Control header
- send Content-Length with each JPEG
- This is how other IP cameras seem to send their MJPEG stream and it made, for instance, the Roku app work.

fix mjpeg.cgi to include Content-Length

---

configs/cameras/victure_pc420

This camera/ sensor doesnt like the `SHVFLIP` param and crashes prudynt. It doesnt work anyway so removing it

remove unknown sensor param causing issues

---

overlay/lower/usr/sbin/irled

Summary:
Unlike motors and ircut, the irled script lacks a status reporting option. This patch implements a read option.
Although the underlying gpio script has a read function, this patch bypasses that abstraction to read the sys tree directly. This is a measured and intentional tradeoff. Output from the gpio script is decorated with unwanted formatting codes and superfluous data fields, which can't be disabled. As the intended application for this output is another program, clean and simple output is preferred.
This will be plumbed through to a web api in a future patch, pending reflection on the most natural way to mesh that feature with the existing APIs.
The targeted application is an unpublished Android mobile application for viewing and controlling thingino pan-tilt cameras on a …

irled: Implement option to read irled state

---

package/thingino-webui/files/var/www/x/plugin-motion.cgi

use a temporary file to avoid a conflict with /tmp/motion directory

webui: fix error when saving motion plugin

---

package/thingino-webui/files/var/www/x/j/motor.cgi

Summary:
The motor.cgi script accepts an "x" url parameter to command motion. The underlying motors command does not support an x argument, and this parameter has no effect because it hits an error in the cgi script:
```
testcam # motors -d x -x 0 -y 0
Invalid Direction Argument x
Usage : motors -d
s (Stop)
c (Cruise)
b (Go to home position)
h (Set position X and Y)
g (Steps X and Y)
testcam #
```
The motors command supports an h argument, for commanding movement to absolute coordinates:
```
testcam # motors -d h -x 0 -y 0
testcam #
```
This patch replaces the invalid x parameter with a working h parameter, and plumbs the command through to the motors binary.
Testing:
The motors.cgi file was patched locally on a Cinnado D1 camera via the overlay filesystem. The following URLs successfully …

webui: Fix motor cgi parameters for absolute movement

---

overlay/lower/usr/sbin/gpio
overlay/lower/usr/sbin/irled

Summary:
Add a new value option to the gpio script for retrieving the bare value of a gpio. Use that feature, rather than the /sys/class/gpio tree, to read values in the irled script.
Subsequent testing revealed that the gpio directory for the IR LED pin is not available upon boot. The gpio script provides the logic to export the gpio directory. Using the gpio script abstraction allows for reading the gpio without further concern for initialization state.
Testing:
With the patch, after a reboot, testing irled read:
```
test # irled read
0
test # irled on
test # irled read
1
test #
```
After another reboot, testing gpio value option:
```
test # ls /sys/class/gpio/
export      gpio57      gpio58      gpio8       gpiochip0   gpiochip32  gpiochip64  unexport
test # gpio value 9
0
test #
``` …

irled: Use gpio script to read led value

---

overlay/lower/usr/share/udhcpc/default.script

On firstboot, or if you delete ntp.conf and reboot or restart dhcp, it should be able to recreate ntp.conf.
Right now it doesn't because on startup ntp.conf doesn't exist.

DHCP should replace ntp.conf if missing or default but ignore if set by user

---

package/thingino-webui/files/var/www/onvif/image.cgi
package/thingino-webui/files/var/www/x/image.cgi

This fixes the following error parsing snapshots using the ONVIF plugin in Scrypted:
```
[Snapshot Plugin]: Snapshot failed, falling back to prebuffer RPCResultError: Parse Error: Invalid header value char
[Snapshot Plugin]:     at Socket.socketOnData (node:_http_client:540:22)
[Snapshot Plugin]:     at Socket.emit (node:events:519:28)
[Snapshot Plugin]:     at Socket.emit (node:domain:488:12)
[Snapshot Plugin]:     at addChunk (node:internal/streams/readable:559:12)
[Snapshot Plugin]:     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
[Snapshot Plugin]:     at Socket.Readable.push (node:internal/streams/readable:390:5)
[Snapshot Plugin]:     at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
[Snapshot Plugin]:     at TCP.callbackTrampoline …
```

webui: add CRLF to image.cgi HTTP headers for correct response formatting

---

Config.in
package/faac/0001-reduce-max-channels-save-ram.patch
package/faac/Config.in
package/faac/faac.mk
package/prudynt-t/Config.in
package/prudynt-t/prudynt-t.mk

Accompanying buildroot PR for Prudynt-T to support AAC encoding and save on bandwidth: https://github.com/gtxaspec/prudynt-t/pull/25
This replaces https://github.com/themactep/thingino-firmware/pull/180

prudynt-t: build faac for AAC audio encoding

---

package/prudynt-t/files/configs/wyze_c3_t31al_atbm
package/prudynt-t/files/configs/wyze_c3_t31x_atbm
package/prudynt-t/files/configs/wyze_c3_t31x_rtl
package/prudynt-t/files/device_presets
package/prudynt-t/prudynt-t.mk

This adds a nice go-to-market feature of audio defaults per camera device so it can be plug-and-play as much as possible versus stock firmwares. I only own Wyze V3 cameras so I'll be adding those for now. Anyone else can add their own defaults to the directory and the script will pick it up.
This isn't exclusive to audio, we can also tweak any other setting in prudynt-t per-device.

prudynt-t: add device preset audio configurations

---

overlay/lower/etc/init.d/S42wireguard
package/thingino-webui/files/var/www/x/config-wireguard.cgi

Added a web-ui for WireGuard. Only handles simple cases, but this works well enough for me to have a remote camera behind a NAT somewhere, connecting back to my VPN where it can then be contacted by my NVR.

web-ui to configure wireguard, and associated startup script

---

package/thingino-webui/files/var/www/x/config-wireguard.cgi

There's a panel showing tunnel state, and a Big Red Switch to control the tunnel state on demand - no reboot required.
Removed some unnecessary stuff (`-E` and `sort`) from the environment output.

allow wireguard page to start/stop the tunnel

---

package/motors/files/S09motor
package/thingino-webui/files/var/www/x/config-motors.cgi

Creates a new uboot env var `motor_speed` that sets the default motor speed for PTZ.
The webui is updated to allow viewing and modifying this value.
If no speed is specified, the S09motor init script uses 900 as the default.
Closes #225

Add motor_speed env var to S09motor and webui

---

package/thingino-webui/files/var/www/x/_motors.cgi

The destructuring assignment to xpos and ypos overlooked their nesting within the message key.

webui: fix (undefined, undefined) motor position in preview

---

package/thingino-webui/files/var/www/x/config-prudynt.cgi

Currently the toggle for audio_enabled on streams does nothing, this fixes the issue.

webui: add `audio_enabled` to `stream_params`

---

package/prudynt-t/files/S96record

prudynt.cfg contains a mix of both
key: value
and
key = value
support both formats, with optional whitespace before and after separator, as they seem to be added by prudynt upon parameter update
fixes #220

prudynt.cfg contains a mix of k:v and k=v, support both fmts

---

overlay/lower/etc/default/ntp.conf

Current ntp pool *.he.net has ping delays of 100-200ms from asia/europe.
Replace with auto-localized global pool, just like openwrt project.
With *.pool.ntp.org, ping roundtrip drop to a reasonable 2-5msec.

ntp: use worldwide auto-localized ntp pool from ntppool.org

---

overlay/lower/usr/lib/mdev/automount

```
before:
/dev/mmcblk0p1 on /mnt/mmcblk0p1 type exfat (rw,sync,relatime,fmask=0000,dmask=0000,allow_utime=0022,namecase=0,errors=remount-ro)
after:
/dev/mmcblk0p1 on /mnt/mmcblk0p1 type exfat (rw,sync,noatime,fmask=0000,dmask=0000,allow_utime=0022,namecase=0,errors=remount-ro)
```

automount: mount sdcard with noatime

---

overlay/lower/etc/init.d/S49ntpd
overlay/lower/etc/ntpd_callback
package/thingino-webui/files/var/www/x/config-time.cgi

Add a file /tmp/sync_status that signals that ntp time is synchronized.
Scripts that depend on synchronized time, for example writing files with correct timestamps, can wait for existence of the file using:
```
#!/bin/sh
while [ ! -e "/tmp/sync_status" ]; do
sleep 1;
done
echo "time synchronized! proceeding..."
```
Added also current sync status in config-time web ui:

ntp: create /tmp/sync_status when ntp is synchronized + webui

---

package/thingino-webui/files/var/www/x/plugin-motion.cgi

During my investigations on how to enable/disable motion detection from my own scripts I noticed a malformed WS communication.  It's only on when the WS is first opened, so it's not very impactful.

Add missing close curly bracket from initial ws open

---

package/onvif-simple-server/0002-change-config-file-and-dir-names.patch
package/onvif-simple-server/files/onvif.conf
package/onvif-simple-server/onvif-simple-server.mk

The last update of onvif_simple_server implements media2 methods.
And onvif.conf needs to be changed to contain new parameters.

Update onvif_simple_server to the last commit

---

package/thingino-webui/files/var/www/x/config-wlan.cgi

Show wifi connection status, connection quality (rssi, phy rates), and connection statistics in the wifi config web page.
This works for at least 50% of the thingino devices (Altobeam), maybe more (can't test all devices).
Perfect is the enemy of the good enough, yada yada, patches welcome
Sample below
```
wlan0     common:
ssid=Home
rssi=-26
mac:00:11:22:aa:bb:cc
tx_pkt=614363
tx_suc_pkt=608973
rx_pkt=537659
tx_rate=650
rx_rate=650
idle=957
throughput=8507131 Byte/s
```

webui: show wifi connection statistics

---

environment/jooan-a6m-atbm6012bx.uenv.txt
environment/jooan-a6m-ssv6355.uenv.txt

(2nd try. ignore the first pull request)
tested 24 hrs, including simultaneous local recording and streaming.
according to T23 calculator:
stream0 = 720p
stream1 = 360p
stream2 = jpeg
buffer = 2M (twice than the recommended buf=1M for 720p)
requires 12M rmem
related #54

env: jooan a6m: decrease rmem from 22M to 12M (2)

---

overlay/lower/etc/ntpd_callback
package/thingino-webui/files/var/www/x/config-time.cgi

ntpd fixes and cleanup:
* move to /run/sync_status
* create /run/sync_success only when time is synchronized successfully, ignoring ntpd periodic messages which can appear even if not synced yet.
* document script usage
* normalize all content in /run/sync_status to the key=value format, including ntpd action field
Sample:
$ cat /run/sync_status
action=periodic
freq_drift_ppm=-2
offset=0.002793
poll_interval=4096
stratum=3
timestamp=2024-10-25T04:38:05
fixes #274

ntpd: move sync status to /run, cleanup

---

package/wifi/files/wlan

two fixes:
1. stempC = Signed temp C = temperature can be negative. accept optional "-" prefix in number regexp for negative numbers.
2. temperature value should contain at least 1 digit. zero digits is invalid value.

wlan: fix temperature regexp

---

package/thingino-webui/files/var/www/x/config-record.cgi

Make recording filenames ISO8601 and Windows compliant (remove colons)
Description:
This pull request updates the filename format for recordings to ensure compliance with both ISO8601 standards and Windows file naming restrictions, specifically by removing colons (":") from the timestamp and using a full date-time format.
Changes:
* Updated the record_filename format in package/thingino-webui/files/var/www/x/config-record.cgi:
`Original format: thingino/%Y-%m-%d/%H:%M:%S`
`New format: thingino/%Y-%m-%d/%Y-%m-%dT%H-%M-%S`
* The new format includes the full date in the filename, so if a file is moved out of its date directory, it will retain the complete timestamp information.
Rationale:
* Ensures compatibility with Windows, which does not support colons in filenames.
* Allows for a full …

record: ISO8601 and Windows compliant filenames no colons

---

package/thingino-portal/files/index.cgi

Users are not aware that portal is time-sensitive, they need to fill out the form within 5 minutes or it will fail.
add alert:
```
For security, portal will automatically shutoff after 5 minutes.
Power-cycle camera to re-activate portal.
```

thingino-portal: inform user of 5min time limit

---

package/thingino-webui/files/var/www/x/plugin-timelapse.cgi

Change the default timelapse filename pattern to include a 'T' separator
between date and time components (%Y%m%dT%H%M.jpg instead of
%Y%m%d%H%M.jpg), aligning with ISO 8601 datetime format.
The 'T' separator improves readability and makes it easier to parse - it's easier for users to quickly
parse "20240105T1430.jpg" into "2024-01-05 14:30" mentally than when
looking at the unbroken "202401051430.jpg", and makes it easier to parse with standard libraries.

timelapse: Use ISO-style datetime format for default filename

---

package/thingino-webui/files/var/www/x/_common.cgi
package/thingino-webui/files/var/www/x/_header.cgi

Wifi adhoc mode is a decentralized mesh protocol (IBSS).
This is not the correct term here.
Replace with Wifi AP term, which is the correct description of the WiFi mode.

wifi: rename adhoc to ap

---

scripts/binpadder.sh

There is no such thing. :)
```
./binpadder.sh: line 33: break: only meaningful in a `for', `while', or `until' loop
```

Remove breaks from bash case

---

overlay/lower/usr/sbin/sysupgrade

current version of the script has a typo and fails to complete:
```
root@wyze-v3-kitchen ~# sysupgrade -p -b
Run as /sbin/sysupgrade -p -b
Updating self
############################################################################################################################################################################################################################################################################# 100.0%############################################################################################################################################################################################################################################################################# 100.0%Re-running script from /tmp/sysupgrade
Run as /tmp/sysupgrade/sysupgrade -p -b
Upgrading from …
```

Fix typo in sysupgrade

---

package/thingino-webui/files/var/www/x/tool-upgrade.cgi

Adds an Upgrade UI option in the web front end for easy upgrades

Webui tool upgrade

---

environment/howell-qj05t.uenv.txt

According to my tests, these thresholds makes sense for this camera.

Add day/night mode gain thresholds to Howell QJ05T

---

package/thingino-webui/files/var/www/x/config-wireguard.cgi

The link to the VPN configuration page is wrong. This PR will fix it by sending to the correct page.
See https://discord.com/channels/1086012062649565286/1209383244710027284/1333499657912975360

use the correct Wiki link for the VPN configuration page

---

overlay/lower/usr/sbin/send2telegram

Fixed the problem where Android couldn't see which apps to use with the video files.

Fixed send2telegram file extension

---

package/prudynt-t/files/record

for record of 60 seconds, line up the recordings to the zero second mark by adjusting the length.
for recordings  val % 60 upto 3600 correct the bound to the nearest by reducing length of the current video
add a timeout to openRTSP to avoid runaway that exceeds expected run length

Record sync

---

package/thingino-webui/files/www/x/config-streamer.cgi
package/thingino-webui/files/www/x/preview.cgi
package/thingino-webui/files/www/x/service-motion.cgi

The way it currently works, in the CGI webpages, the port to seek websocket is hardcoded to the value 8089. This value works because prudynt uses that port for providing unencrypted websocket connection, which is used for the camera preview.
This, however, causes an issue in camera preview when getting SSL to work by wrapping the http stream with a reverse proxy. The problem is that now port 8089 is expecting to provide WSS connection instead of WS, which breaks the stream.
This PR provides a simple (perhaps temporary) solution to this problem. If any of the CGI files that use websocket detect that the webpage is using SSL protocol, it uses port 8090 instead of 8089.
This solution was tested with stunnel (being the reverse proxy), and it works.
To test it:
1. Add `BR2_PACKAGE_STUNNEL=y` …

Make connection destination for Websocket with SSL (WSS) use port 8090, which helps in supporting both http and https

---

package/thingino-motors/files/S09motor

Fixed Homing On Boot by making motor_pos_0 NOT local in position_motors()
#590

Fixed Homing on boot

---

scripts/manual-wg-setup.sh

The default Thingino WireGuard init script fails to assign the interface IP, resulting in a successful handshake but no routed traffic.
This PR introduces a manual interactive setup script that fully replicates a known-good configuration using `ip` and `wg`, bypassing the init logic entirely.
Fix tested on hardware where `/etc/init.d/S42wireguard` produced:
```
No WireGuard IP address configured
```
Closes #682.

fix: add manual WireGuard setup script to restore routing

---

.gitignore

The `download-cache` option in the user menu downloads the cache zip in the checkout root, add it to gitignore to avoid accidentally polluting the working set.

gitignore: add buildroot-dl cache

---

configs/cameras/aobocam_a12_t23dl_jxh63p_txw901u/aobocam_a12_t23dl_jxh63p_txw901u.uenv.txt

This is the full gpio mapping extracted from the factory firmware:
```
GPIOs 0-31, GPIO A:
gpio-18  (jxh63p_reset        ) out hi
GPIOs 32-63, GPIO B:
gpio-49  (sysfs               ) out hi
gpio-51  (sysfs               ) out lo
gpio-52  (mmc_detect          ) in  lo
gpio-53  (sysfs               ) out lo
gpio-54  (sysfs               ) out hi
gpio-57  (sda                 ) in  lo
gpio-58  (scl                 ) in  lo
gpio-59  (sysfs               ) in  hi
gpio-61  (sysfs               ) out hi
gpio-62  (sysfs               ) in  hi
gpio-63  (sysfs               ) in  lo
GPIOs 64-95, GPIO C:
gpio-91  (sda                 ) in  lo
gpio-92  (scl                 ) in  lo
```
Let me know if any of them are useful and should be also added to the camera env config.

Aobo A12: configure gpios

---

overlay/lower/usr/sbin/send2telegram
package/thingino-webui/files/www/x/service-motion.cgi

I stopped a memory leak which resulted in degraded performance and crashes from send2telegram program. The lack of removal of temporary files from abnormal exits in other send2[X] programs can also cause crashes, I didn't fix them as I couldn't test them for stability improvements.
For some reason increasing the cooldown time between the motion alarms stopped my remaining crashes. I couldn't figure out the exact cause behind it, but changing the cooldown range on the GUI could help other users who experience similar issues.

Improved Motion Guard Stability

---

package/prudynt-t/prudynt-t.mk

Constant CPU load on T23:
```
Mem: 34228K used, 3284K free, 716K shrd, 3920K buff, 13960K cached
CPU: 24.7% usr 49.3% sys  0.0% nic  0.0% idle  0.0% io  0.0% irq 25.9% sirq
Load average: 2.97 3.09 3.50 2/85 20561
PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
20507     1 root     S    44780119.1   0 92.9 /bin/prudynt --
```

disable two-way audio for low-memory devices

---

overlay/lower/usr/sbin/telegrambot

This fixes two things:
1. The $result variable does not exist in the script, so it is always evaluated into an empty string.
2. The $message variable is set to the stdout of the command, ignoring stderr. This once again causes $message to be empty if an error occurs.
This can be tested by opening the web UI and adding a bot command that will always fail (like `ls /abc`), and then sending that command to the bot on Telegram.
Hope this helps!

Fix error output in telegrambot
